/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.helloworld;

/**
 *
 * @author aluno
 */
public class FrameHelloWorld extends javax.swing.JFrame {

    /**
     * Creates new form FrameHelloWorld
     */
    public FrameHelloWorld() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_title = new javax.swing.JLabel();
        BT_botao_principal = new javax.swing.JButton();
        TX_texto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        LB_title.setBackground(new java.awt.Color(255, 255, 255));
        LB_title.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        LB_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LB_title.setText("Hello World");
        LB_title.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        BT_botao_principal.setBackground(new java.awt.Color(0, 0, 0));
        BT_botao_principal.setForeground(new java.awt.Color(255, 255, 255));
        BT_botao_principal.setBorder(null);
        BT_botao_principal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BT_botao_principal.setLabel("Alterar Texto");
        BT_botao_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_botao_principalActionPerformed(evt);
            }
        });

        TX_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TX_textoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TX_texto)
                    .addComponent(LB_title, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 278, Short.MAX_VALUE)
                        .addComponent(BT_botao_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TX_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(BT_botao_principal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_botao_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_botao_principalActionPerformed
        String nome = TX_texto.getText();
        LB_title.setText(nome);
        
    }//GEN-LAST:event_BT_botao_principalActionPerformed

    private void TX_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TX_textoActionPerformed
        
    }//GEN-LAST:event_TX_textoActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_botao_principal;
    private javax.swing.JLabel LB_title;
    private javax.swing.JTextField TX_texto;
    // End of variables declaration//GEN-END:variables
}
